classDiagram
    class User {
        citizen_id: String
        name: String
    }
    
    class Account {
        account_number: String
        balance: Float
        transactions: List
    }
    
    class Transaction {
        transaction_type: String
        amount: Float
        atm_id: String
        balance: Float
        transfer_account: String
    }
    
    class ATMCard {
        card_number: String
        pin: String
        annual_fee: Float
        daily_withdrawal_limit: Float
    }
    
    class ATMMachine {
        machine_id: String
        balance: Float
    }
    
    class Bank {
        users: List
        accounts: List
        cards: List
        atms: List
    }
    
    User "1" --> "1" Account : Owns
    Account "1" --> "*" Transaction : Records
    ATMCard "1" --> "1" Account : Links
    ATMMachine "*" --> "1" Bank : Belongs
    Bank "1" --> "*" User : Manages
    Bank "1" --> "*" Account : Holds
    Bank "1" --> "*" ATMCard : Issues
