classDiagram
    class CEO {
        Login: String
        Password: String
    }
    
    class Project {
        ID: Number
        TasksID: Number[]
        Access: Number[]
        Name: String
    }
    
    class Report {
        Time: Number
        Date: Date
        Task: String
        Project: String
    }
    
    class Employee {
        ID: Number
        Login: String
        Password: String
    }
    
    CEO "1" --> "*" Project : Manages
    CEO "1" --> "*" Report : Controls
    CEO "1" --> "*" Employee : Assigns
